### PR TITLE
Add bind address argument.

### PR DESCRIPTION
**Pull request by midicase**
To do multicast on multi-homed systems would currently require an entry in the routing table, which we avoid in production systems (some will have 6 interfaces with more than 1000 streams).

### CODE REVIEW

**Comment by midicase** [comment]
Not thoroughly tested. Feel free to rework as needed.  I need to spool a stream out to generate a pcap for dev testing.

**Comment by futzu** [comment]
I just pushed a fix and then saw your pull request. If mine doesnt work for you, I'll roll it back and merge your pull request, cool?

**Comment by futzu** [comment]
We did it two different ways, I'm going to check  the Steven's Book, _Advanced Programming in the UNIX Environment_ to see if I can get clarification.
I think I can actually use them both if needed.

You  did 
```py3
  if self.bindaddr:
            sock.setsockopt(socket.SOL_IP, socket.IP_ADD_MEMBERSHIP, socket.inet_aton(self.mcast_ip) + socket.inet_aton(self.bindaddr))
```
I did
```py3
        sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_IF, socket.inet_aton(self.nethost))

```

I could do both, if needed, like this 
```py3
sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_IF, socket.inet_aton(self.nethost))
if self.nethost != '0.0.0.0':
            sock.setsockopt(socket.SOL_IP, socket.IP_ADD_MEMBERSHIP, socket.inet_aton(self.mcast_ip) + socket.inet_aton(self.nethost))

```

**Comment by futzu** [comment]
Stevens has nothing on multicast, so I googled a bit and I found several examples done as you did, several done as I did, a few other ways here:

https://www.programcreek.com/python/example/101859/socket.IP_MULTICAST_IF

Easiest way I can think to test is to run 
```
tcpdump multicast -n

19:43:34.356395 IP 192.168.12.160.37780 > 235.35.3.5.3535: UDP, length 1316
19:43:34.356405 IP 192.168.12.160.37780 > 235.35.3.5.3535: UDP, length 1316
19:43:34.356424 IP 192.168.12.160.37780 > 235.35.3.5.3535: UDP, length 1316
19:43:34.356437 IP 192.168.12.160.37780 > 235.35.3.5.3535: UDP, length 1316
19:43:34.356446 IP 192.168.12.160.37780 > 235.35.3.5.3535: UDP, length 1316
19:43:34.356457 IP 192.168.12.160.37780 > 235.35.3.5.3535: UDP, length 1316
19:43:34.356465 IP 192.168.12.160.37780 > 235.35.3.5.3535: UDP, length 1316



```

**Comment by futzu** [comment]
I put them both together and added converting the ttl to bytes, for OpenBSD  and other BSD based stuff. 
that v.0.0.12. Git pull it and see if that works for you.

**Comment by futzu** [comment]
At least on Linux, Multicast will only go out one interface,  and IP_MULTICAST_IF is the way to specify it.

`If the host has more than one interface and the IP_MULTICAST_IF option is not set, multicast transmissions are sent from the default interface, although the remaining interfaces might be used for multicast forwarding if the host is acting as a multicast router.` 

From the Linux Multicast Howto: https://tldp.org/HOWTO/Multicast-HOWTO-6.html#ss6.3

6.3 IP_MULTICAST_IF.

Usually, the system administrator specifies the default interface multicast datagrams should be sent from. The programmer can override this and choose a concrete outgoing interface for a given socket with this option.

    struct in_addr interface_addr;
    setsockopt (socket, IPPROTO_IP, IP_MULTICAST_IF, &interface_addr, sizeof(interface_addr));

`From now on, all multicast traffic generated in this socket will be output from the interface chosen.` To revert to the original behavior and let the kernel choose the outgoing interface based on the system administrator's configuration, it is enough to call setsockopt() with this same option and INADDR_ANY in the interface field.

**Comment by futzu** [comment]
Ill package up 0.0.13 so you can pip install. 

This is only needed for receiving
```py3
    sock.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, socket.inet_aton(address) + socket.inet_aton(network_adapter))
```

These are the rules as I understand them. I tested on OpenBSD 7.0, and Debian Sid.

*  Using  the -n or --nethost will send from the nethost interface, even if a route has been added or the default set .


* 0.0.0.0 as nethost, the default, will send it out the default interface.

* On linux you can set the default interface for multicast  with 
```sh
ip link set  wlp1s0 multicast on allmulticast on
```

* To send from a aliased ip on an  interface  you have to add a route  for the alias ip  
    ```sh
    route add 224/4 206.125.170.46 
   ```

**Comment by futzu** [comment]
I deleted my multicast routes and it worked just fine, you will  have to enable multicast on the interfaces being used, but routes wont be needed unless you are using an aliased ip on an interface.

**Comment by midicase** [comment]
It's nice to have options in the application since setting kernel level routes is a priviledged operation.  The other item that may of interest, drawing from memory here, IP_ADD_MEMBERSHIP tells the [Linux] kernel to send periodic igmp requests to upstream routers to keep the multicast feed.  See IGMP snooping for more info.  I did not test or check for outbound which does need a different syscall.

**Comment by futzu** [comment]
I definitely think this has been a big improvement, and it forced me to verify some details, and fix the ttl so it worked correctly with BSD based stuff. 

So let me make sure I understand the situation. You have 9 NICS in the server, 1000 streams and you want to be able to send streams out different NICS, correct? 

Were you just doing unicast UDP with ffmpeg and letting the normal network routing determine the NIC?

You'll like this too, I am about to turn on continuity counter checking  for six2scte35,  that let will let you know if packets are dropped on the way in.

**Comment by futzu** [comment]
[fu.py.gz](https://github.com/futzu/gumd/files/10934865/fu.py.gz)

Try this one, its unicast UDP

just un-gzip it and chmod +x

you can pipe to it just like gumd

```js
usage: fu.py [-h] [-i INPUT] [-a ADDR]

optional arguments:
  -h, --help            show this help message and exit

  -i INPUT, --input INPUT
                        like "/home/a/vid.ts" or "udp://@235.35.3.5:3535" or
                        "https://futzu.com/xaa.ts" default is stdin.

  -a ADDR, --addr ADDR  like "127.0.0.1:1234", default is 127.0.0.1:1234

```

**Comment by midicase** [comment]
Unicast is not a problem. ffmpeg has localaddr option to bind to specific interface for transmitting or receiving:

`ffmpeg -re -i INPUT -c copy -f mpegts 'udp://239.4.5.6:2000?localaddr=192.168.2.2&pkt_size=1316&flush_packets=0'`

I've learned it is best to stay out of the system route table and programmatically managing it in C/C++ is pretty painful (netlink socket api).  

Edit: typo

**Comment by futzu** [comment]
I'm adding unicast udp to gumd now. 

```js
video_stream | gumd -a 1.2.3.4:5000 --udp
```

**Comment by futzu** [comment]
```js
pypy3 -mpip install --upgrade gumd
```

**Comment by futzu** [comment]
Oh good God, I figured it out, you would think the name of the pull request would have made it obvious, 
All I have to do is bind to the local ip and even aliased ip addresses work. 
We don't even need 
```js
sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_IF, socket.inet_aton(self.nethost))
```
give me a minute and Ill do another package.

**Comment by futzu** [comment]
I should have listened to you, you were more right than I was
```js
pypy3 -mpip install --upgrade gumd

```
v.0.0.15 is what you want
_the options have changed a bit_

```js
a@debian:~/gumd$ gumd -h
usage: gumd [-h] [-i INPUT] [-a ADDR] [-u] [-b BIND_ADDR] [-t TTL] [-v]

optional arguments:
  -h, --help            show this help message and exit
  -i INPUT, --input INPUT
                        like "/home/a/vid.ts" or "udp://@235.35.3.5:3535" or "https://futzu.com/xaa.ts"
  -a ADDR, --addr ADDR  Destination Address:Port like "227.1.3.10:4310"
  -u, --unicast         Use Unicast instead of Multicast
  -b BIND_ADDR, --bind_addr BIND_ADDR
                        Local IP and Port to bind to like "192.168.1.34:5555". Default is "0.0.0.0:1025"
  -t TTL, --ttl TTL     Multicast TTL 1 - 255
  -v, --version         Show version




```

**Comment by midicase** [comment]
Is a bind port required?  I usually let the system pick one since there is a chance the one I "pick" is already in use by another service.

**Comment by futzu** [comment]
> Is a bind port required? I usually let the system pick one since there is a chance the one I "pick" is already in use by another service.

That's a good question. According to the docs:
>As server programs listen on published ports, it is required that a port and the IP address to be assigned explicitly to a server socket.

hmmm, let me look into for a minute.  I believe we can do socket reuse, or if nothing else, I can have it try to bind, and then increment the port number by 1 and try again. Which is similar to how NFS does it when portmap isn't available.

**Comment by futzu** [comment]
Just use a 0 and the kernel assigns a random high port.

I ran 2 gumd processes both bound to 192.168.12.160:0
```js
a@debian:~/gumd$ cat ~/mpegts/plp0.ts |gumd -b 192.168.12.160:0 -a 127.0.0.1:4444 -u
Stream Uri: udp://127.0.0.1:4444 from source 192.168.12.160:0

``` 
and 
```js
a@debian:~/gumd$ cat ~/mpegts/plp0.ts |gumd -b 192.168.12.160:0 -a 127.0.0.1:55555 -u
Stream Uri: udp://127.0.0.1:55555 from source 192.168.12.160:0
```
then I ran `tcpdump -n -i lo udp`
```js
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on lo, link-type EN10MB (Ethernet), snapshot length 262144 bytes
16:35:37.839798 IP 192.168.12.160.58681 > 127.0.0.1.4444: UDP, length 1316
16:35:37.839799 IP 192.168.12.160.52328 > 127.0.0.1.55555: UDP, length 1316
16:35:37.839810 IP 192.168.12.160.58681 > 127.0.0.1.4444: UDP, length 1316
16:35:37.839816 IP 192.168.12.160.52328 > 127.0.0.1.55555: UDP, length 1316
16:35:37.839825 IP 192.168.12.160.58681 > 127.0.0.1.4444: UDP, length 1316
16:35:37.839835 IP 192.168.12.160.58681 > 127.0.0.1.4444: UDP, length 1316
```

**Pull request closed without merging**
